---

- name: Add Docker GPG apt Key
  apt_key:
    url: "{{ docker_repo }}{{ ansible_distribution | lower }}/gpg"
    state: present

- name: add docker official repository for {{ ansible_distribution }}
  apt_repository:
    repo: "deb [arch=amd64] {{ docker_repo }}{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_release_br }}"
    state: present

- name: Update apt and install docker-ce
  apt: 
    name: "{{ docker_packages }}"
    state: present

- name: Enable and start service docker
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: started
 
...     
